// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFlLMqP8KpO34bJd6a9KO9sIKJg7mGY5Y',
    appId: '1:515165052280:web:a5df26aadbaeaabe71fc8d',
    messagingSenderId: '515165052280',
    projectId: 'keuangan-ce1d6',
    authDomain: 'keuangan-ce1d6.firebaseapp.com',
    databaseURL: 'https://keuangan-ce1d6-default-rtdb.firebaseio.com',
    storageBucket: 'keuangan-ce1d6.firebasestorage.app',
    measurementId: 'G-K392WRRPTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTldKdPefI1Sfs2K9NzCpXGh-oaQ23ueY',
    appId: '1:515165052280:android:9a891c90b1f222e771fc8d',
    messagingSenderId: '515165052280',
    projectId: 'keuangan-ce1d6',
    databaseURL: 'https://keuangan-ce1d6-default-rtdb.firebaseio.com',
    storageBucket: 'keuangan-ce1d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDFC17en7MsMBNvOQYt_oiOBTeAqhw_o',
    appId: '1:515165052280:ios:c695bd129280311d71fc8d',
    messagingSenderId: '515165052280',
    projectId: 'keuangan-ce1d6',
    databaseURL: 'https://keuangan-ce1d6-default-rtdb.firebaseio.com',
    storageBucket: 'keuangan-ce1d6.firebasestorage.app',
    iosBundleId: 'com.uangnote.erditya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDFC17en7MsMBNvOQYt_oiOBTeAqhw_o',
    appId: '1:515165052280:ios:c695bd129280311d71fc8d',
    messagingSenderId: '515165052280',
    projectId: 'keuangan-ce1d6',
    databaseURL: 'https://keuangan-ce1d6-default-rtdb.firebaseio.com',
    storageBucket: 'keuangan-ce1d6.firebasestorage.app',
    iosBundleId: 'com.uangnote.erditya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFlLMqP8KpO34bJd6a9KO9sIKJg7mGY5Y',
    appId: '1:515165052280:web:72921d53b58479c871fc8d',
    messagingSenderId: '515165052280',
    projectId: 'keuangan-ce1d6',
    authDomain: 'keuangan-ce1d6.firebaseapp.com',
    databaseURL: 'https://keuangan-ce1d6-default-rtdb.firebaseio.com',
    storageBucket: 'keuangan-ce1d6.firebasestorage.app',
    measurementId: 'G-D7ZYRJNXN8',
  );

}